
services:
  server:
    image: backend
    ports:
      - 5000:5000
    env_file: .env 
    networks:
      - localnet


  client:
    image: frontend
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - localnet


  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - localnet

volumes:
  mongodbdata:


networks:
  localnet:
