
services:
  server:
    build:
      context: ./server
    ports:
      - 5000:5000
    env_file: .env 
    develop:
      watch:
        - path: ./server/src
          action: sync
          target: /usr/local/app/src
        - path: ./server/package.json
          action: rebuild
    networks:
      - localnet


  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
    depends_on:
      - server
    networks:
      - localnet


  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - localnet

volumes:
  mongodbdata:


networks:
  localnet:
