
services:
  server:
    image: dockerdevrel/wad-todo-backend
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
      - JWT_SECRET=603b31XXXXXXX90d3b8cb62f0a585fd70a5ee0b4d
      - AWS_ACCESS_KEY_ID=AKIAXXXXXDDDX
      - AWS_SECRET_ACCESS_KEY=hSYXtvXXXXXXXO/k39FGt3u078pYWsh
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=localbuckett
    networks:
      - localnet


  client:
    image: dockerdevrel/wad-todo-frontend
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - localnet


  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - localnet

volumes:
  mongodbdata:


networks:
  localnet:
